# Generated by Django 4.1 on 2022-08-19 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('iso3', models.CharField(max_length=3)),
                ('iso2', models.CharField(max_length=2)),
                ('phone_code', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=8)),
                ('currency_symbol', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatacentersModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('905ca993-cfab-4a9d-bfd0-9f074fda0610'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=56)),
                ('code', models.CharField(max_length=8)),
                ('region', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'datacenters',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state_code', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='hello.countrymodel')),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('905ca993-cfab-4a9d-bfd0-9f074fda0610'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=16)),
                ('job_title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('line1', models.CharField(blank=True, max_length=256, null=True)),
                ('line2', models.CharField(blank=True, max_length=256, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_picture', models.TextField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cities', to='hello.citymodel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_countries', to='hello.countrymodel')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='hello.statemodel')),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('905ca993-cfab-4a9d-bfd0-9f074fda0610'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to='hello.datacentersmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='hello.userprofilemodel')),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkspaceModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('905ca993-cfab-4a9d-bfd0-9f074fda0610'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user', to='hello.userprofilemodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='hello.workspacemodel')),
            ],
            options={
                'db_table': 'user_workspaces',
            },
        ),
        migrations.CreateModel(
            name='UserNamesModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('905ca993-cfab-4a9d-bfd0-9f074fda0610'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('provider', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='hello.userprofilemodel')),
            ],
            options={
                'db_table': 'user_names',
            },
        ),
        migrations.AddField(
            model_name='citymodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_countries', to='hello.countrymodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hello.statemodel'),
        ),
    ]
