# Generated by Django 4.1 on 2022-08-23 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacentersmodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0c619d6b-8e21-49a1-b7fb-99192ac9de4e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usernamesmodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0c619d6b-8e21-49a1-b7fb-99192ac9de4e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0c619d6b-8e21-49a1-b7fb-99192ac9de4e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkspacemodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0c619d6b-8e21-49a1-b7fb-99192ac9de4e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspacemodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0c619d6b-8e21-49a1-b7fb-99192ac9de4e'), primary_key=True, serialize=False),
        ),
    ]
